### PR TITLE
extra @tab

### PR DESCRIPTION
**Pull request by pipcet**
Now it looks right in the PDF

### CODE REVIEW

**Comment by rocky** [comment]
Thanks.

**Comment by rocky** [comment]
Had a possibly interesting thought in looking at this. How do you feel about `constant-i1` -> `constant[1]` and so on?

**Comment by pipcet** [comment]
Great idea, let's do that!

**Comment by pipcet** [comment]
Okay, I've played with this a little and finally come up with a notation that I believe is readable and maps back to the existing notation:

* if the argument is part of the opcode byte, as in `constant-i63`, we write `constant[63]`.
* if the argument follows the opcode byte, as in `constant2 64`, we write `constant2 [64]`, with an intervening space to mark the byte boundary

To get back standard Emacs Lisp assembly code, simply omit everything in brackets.

The code's at https://github.com/pipcet/elisp-lap/tree/brackets.

**Comment by rocky** [comment]
Sure. Let's try it!

The project is young enough that we can afford to try new things and back them out if there's problem (which I don't expect here, I just meant that as a principle.)

**Pull request merged**
