### PR TITLE
Bytecode wrt JITs and alternative languages

### PR DESCRIPTION
**Pull request by rocky**
Thoughts?

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
If you're replacing "byte code" with "bytecode", you missed a few places. EDIT: Looks like you fixed this now.

If you want to look into the history of Emacs, I have copies of TECO EMACS (which I use almost daily), Gosling Emacs, and GNU Emacs 13.

As for the future.  I'm a fan of the Common Lisp Emacs idea.  But I don't think it's realistic to replace Emacs Lisp with anything else due to the large amount of great code written already.

**Comment by rocky** [comment]
@larsbrinkhoff If you can give me access to the old emacs's I might be able to fill in the gaps the instructions. If that's not practical, then I'd appreciate it if you filled in the gaps on things like `read-char`, `mark`, `interactivep` and so on. 

As for Common Lisp, what's been happening is that Emacs Lisp has been evolving to be more Common-Lisp compatible. The underlying implementation however hasn't changed (much), and to the extent it has it has been by adding/chaning bytecode instrucitons. I should probably note that.

**Comment by larsbrinkhoff** [comment]
It's entirely practical.  I have placed everything here:  
https://github.com/larsbrinkhoff/emacs-history

**Comment by pipcet** [comment]
Well, I'm obviously biassed, but my SpiderMonkey+Emacs Frankenstein is quite stable now, and I use it every day (shameless plug, sorry). That would allow us to compile to JavaScript, SpiderMonkey bytecode, or IonMonkey IR, from either Emacs bytecode or Emacs Lisp directly. The problem is those are six possibilities...

(I also believe SpiderMonkey bytecode is still in some ways the natural successor to Emacs Lisp bytecode, having been developed by some of the same people.)

I don't think LLVM IR or WebAssembly are natural approaches, falling into the same category as translation to C or using the GCC JIT functionality.

**Comment by rocky** [comment]
@pipcet ok. Fair enough. Never ascribe to maliciousness that which can be easily explained by (my) ignorance. Revise the text as you feel appropriate. It's okay to add links too.

**Comment by rocky** [comment]
Also, some fraction of those 6 possibilities do _not_ obviate the need for Elisp bytecode. Any thoughts on the pros and cons of going directly (eliminating bytecode and its optimizer) versus going via bytecode?

**Review by larsbrinkhoff — APPROVED** [review]

**Comment by larsbrinkhoff** [comment]
It seems to me this speculation about the future of Emacs extension languages is a bit tangential to the stated purpuse of this document.

On the other hand, I very much like these discussions of the future and the past, so forge ahead all you want! :-)

**Review by pipcet — APPROVED** [review]

**Pull request merged**
