### PR TITLE
Note that there may are alternative ways to generate code

### PR DESCRIPTION
**Pull request by rocky**

### CODE REVIEW

**Review by larsbrinkhoff — APPROVED** [review]

**Review by pipcet — APPROVED** [review]
We should probably link to specific bytecode-related projects, too. I'm not sure how much progress there has been on lbforth for ELisp, but the assembler itself is worth mentioning, IMHO.

**Comment by larsbrinkhoff** [comment]
It would be interesting to have a somewhat complete list of programs outside Emacs that use bytecodes.  El compilador springs to mind, but I'm not aware of much else.

**Comment by rocky** [comment]
> It would be interesting to have a somewhat complete list ...

@larsbrinkhoff Yep - please fork and submit a change. Thanks.

**Comment by larsbrinkhoff** [comment]
I'm already way overcommited on other projects.

Searching around like this can provide some interesting results:  
http://github.com/search?q=%22Bsave_current_buffer_1%22+-filename%3Abytecode.c+-filename%3AChangeLog&type=Code

**Pull request merged**
