### PR TITLE
Opcode table tweak...

### PR DESCRIPTION
**Pull request by rocky**
Silence TeX complaints. Some other minor TeX changes

### CODE REVIEW

**Comment by pipcet** [comment]
Hmm, `call6`'s and `call7`'s stack column doesn't appear to fit. The rest looks good to me.

**Comment by rocky** [comment]
Thanks for checking. I think I have it right now.

**Review by pipcet — APPROVED** [review]
Looks good!

**Comment by rocky** [comment]
Saturday, I may start a section on instruction changes as Emacs versions change. I know there is some filling out of instruction descriptions with examples, but I'm holding off on those is that is pretty straightforward.

**Pull request merged**
