### PR TITLE
More on optimization

### PR DESCRIPTION
**Pull request by vkazanov**
I've added a subsection on source-to-source transformations. Next step: a subsection on peephole optimizations and a general clean up of the whole section.

Hopefully we'll should end up with not only a reference but a optimizing framework description.

### CODE REVIEW

**Review by rocky — APPROVED** [review]
Hi - thanks for the opportunity to review. I just looked at everything in totality. Overall it looks great. Here are some suggestions to consider. 

Sometimes I get confused as to whether in an example a transformation is done at the bytecode or lisp level. Take for example: https://github.com/rocky/elisp-bytecode/blob/master/optimization.texi#L174

The optimization is described in LAP instructions, so that seems to indicate that this is transformation is done in LAP. Is it? If not I think it would be better to say `(+ a 1)` generates `(add1 a)`. Same question for https://github.com/rocky/elisp-bytecode/blob/master/optimization.texi#L88  is this done at the LAP or ELisp  level?

In the list around https://github.com/rocky/elisp-bytecode/blob/master/optimization.texi#L88 some of these items like constant folding are elaborated on. It might be cool to add a link to the relevent section(s) where the transformations are expanded upon. 

A very smal grammar thing. Even though `macroexpand` is an Elisp function, when used as an adjectiive I think there is a hypen in there, e.g. "macro-expanded forms". The same thing is true for "in-line functions". There would a stronger case for one word in "function inlined".  (I am channeling my rms pickiness here. If you want to leave as is, that's okay. This section is after all, yours.)

One broad thing that would be cool to work out is to give a real session for how one would work out or debug an optimization. For example, may there is one that you added or would like to add, and show how you worked on adding it. For example suppose one didn't care about bytecode compatibility across different machine word sizes and I wanted to add the floating point constant folding, how would I do that? 

Finally as for mechanics - if you want to merge this and consider  incorporating the suggestions in a future PR that's fine or keep going with this, either is fine. The main thing I care about in the PR is that the buid doesn't break. As is the PR builds fine.

**Comment by vkazanov** [comment]
Thanks for an expanded review! Just what I needed.

I'll fix all the grammar-related things, of course. 

> Sometimes I get confused as to whether in an example a transformation is done at the bytecode or lisp level

The problem with concrete groups of transformations is that there's no single place in the code that is responsible for, say, constant folding. Folding logic is spread over functions in 'byte-optimize properties of various symbols, with lap-code optimization sometimes doing similar things. 

So the real question for you: do we want to list and describe **all** the transformations done? E.g. list the source-level transformations with examples, then list lap-code optimizations... That's a lot of work! :-) 

OTOH, the current approach (try to come up with a categorization of transformations) feels a bit... Not related to reality of the optimizer code, with related transformations spread over many functions. 

> One broad thing that would be cool to work out is to give a real session for how one would work out or debug an optimization.

That's really cool, I like the idea. Will try to come up with something, no promises though.

> if you want to merge this and consider incorporating the suggestions in a future PR that's fine

I'd really like to open PRs in iterations, making sure it's easier for you to go through the text.  Don't mind if I just merge this one after fixing grammar-related and formatting errors?

**Comment by vkazanov** [comment]
I've clean up a bit, added cross-references, commented out the TODO list of optimizations (it's useful for us, not really useful in the book itself).

**Comment by rocky** [comment]
> So the real question for you: do we want to list and describe all the transformations done? E.g. list the source-level transformations with examples, then list lap-code optimizations... That's a lot of work! :-)

Look at the amount of work done (so far) to document the 200+ bytecode operations which is still lacking. Are you saying this is going to be more work that that? As you can see it is perfectly fine to set up a structure that can be expanded upon and fill this out as desired. I've been doing a little each time there is an upvote. 

So my real question to you, and I realy don't know the answer, is whether this would be useful to someone who wants to understand what's going on in the optimizer and possibly contribute or write new optimizations? 

Because the code hasn't been documented and the code is in need of major overhaul, there aren't many peope who would be able to work on it, in its current state. And those that did work on it intiialy like rms and jwz have probably forgotten whatever they knew, even if they wanted work on this more (which they don't). 

> I'd really like to open PRs in iterations, making sure it's easier for you to go through the text. Don't mind if I just merge this one after fixing grammar-related and formatting errors?

Ok. Then merge when you feel it is the right time. However fix the failiing build, please.

**Comment by vkazanov** [comment]
>Look at the amount of work done (so far) to document the 200+ bytecode operations which is still lacking. Are you saying this is going to be more work that that?

Yes, that's a huge amount of work. Too bad I didn't have something like this manual when I started looking into the VM a few years ago.

> So my real question to you, and I realy don't know the answer, is whether this would be useful to someone who wants to understand what's going on in the optimizer and possibly contribute or write new optimizations?

Okay, I'll keep that goal in mind: make the manual useful for someone who intends to work on the optimizer.

> Ok. Then merge when you feel it is the right time. However fix the failiing build, please.

Will do. I think my version of texinfo is different, as it doesn't give me any warnings.

**Comment by rocky** [comment]
> Will do. I think my version of texinfo is different, as it doesn't give me any warnings.

It is `makeinfo`  that is failing. And that is often the case. It is finicky about how the sections link together.  I'd've ditched it a while ago were it not the GNU thing to do and this is supposed to be a GNU thing.

**Comment by rocky** [comment]
(Note attached to individual lines in last commit: See the `@SECTION`,  `@Subsection`, and `@FirstSubsection` macros.

**Comment by vkazanov** [comment]
Oh. I didn't realize those macros waere case sensitive! Is there some kind of texi style guide you used for the document?

**Comment by rocky** [comment]
No style guide. If you look at the commit's it's been just me. And in terms of style, I don't really have much to say.

**Pull request merged**
